### ISSUE TITLE
Can't find Config Option 'Edit Mode'

### ISSUE THREAD

**Issue by AidanR8459** [tr7zw/ItemSwapper#106]
Hi @tr7zw and @Xisuma 

I found this video:
[Make Your Own Item Swapper Pallets!](https://www.youtube.com/watch?v=jpJxeDg9daU)
But on the latest version of the mod (0.3.2/1.19.3) i can't find Edit Mode with Mod Menu.
Do you have any idea why?

Kind Regards,
AidanPlayz8459

**Comment by tr7zw** [comment]
Xisuma used an old version for that video, the updated name is "Preview Mode".
