### ISSUE TITLE
Server Popup removal/limit.

### ISSUE THREAD

**Issue by AmyMialee** [tr7zw/ItemSwapper#108]
It feels quite irritating that the server popup happens every time I join the server, despite that it's the same server each time, it would be nice to have a way to disable it after the first occurrence, or even just a config to disable it entirely to avoid needing to store a list of servers it's been used on.

**Comment by AdvancedWipe** [comment]
Yes indeed that's quite annoying. I am current working on a fix.

**Comment by tr7zw** [comment]
Was added in the pr, and might still get changed in the future.
