### ISSUE TITLE
Make empty bottles swappable with potions

### ISSUE THREAD

**Issue by pointwoods** [tr7zw/ItemSwapper#11]
The potion swapping is cool, but it's disappointing that it doesn't work with empty bottles.  You can only swap a filled bottle with another filled bottle, limiting it's actual utility when drinking multiple potions.

**Comment by jbraunschweiger** [comment]
Adding bottles to the potion palette fixes the issue for normal potions but not splash potions, see #74 for my thoughts

**Comment by pointwoods** [comment]
If you just have it so the mod will automatically swap out your splash potion with another from you inventory once used, you could bypass the need to have an entire separate keybind for potions while keeping the utility of the potion switcher for splash potions.

 This could introduce some balancing issues but I think the impact would be minimal considering the mod is not really intended for competitive pvp scenarios

**Comment by jbraunschweiger** [comment]
I like that too. Honestly I think potions should be stackable to 4 or 16 with a cooldown like enderpearls, snowballs, etc. But that seems out of scope of this mod.

**Comment by tr7zw** [comment]
To be fair, thats part of the combat update, unrelated to this mod.

**Comment by tr7zw** [comment]
Has been in the mod for some time.
