### ISSUE TITLE
Middle Click Pulls From Shulker

### ISSUE THREAD

**Issue by tr7zw** [tr7zw/ItemSwapper#115]
### Discussed in https://github.com/tr7zw/ItemSwapper/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **nickadactyl** December 16, 2022</sup>
Quick idea I just now while playing, if you could pull items from shulkers in your inventory by middle-clicking I think that would help the inventory issue a ton. It's another way to avoid constantly placing shulkers down while you're mid build. </div>

**Comment by tr7zw** [comment]
Added.

**Comment by Vaskyy** [comment]
> Added.

What does that mean? Feature added? Issue added.. ?
Since ur comment there was no new version published. So .... ?

**Comment by tr7zw** [comment]
Correct, no new version published since, but it is in the current dev version(downloadable from the Actions tab above).
