### ISSUE TITLE
Config option to disable moving as if you were in inventory while itemswapper is being used

### ISSUE THREAD

**Issue by TheDerpu0ne** [tr7zw/ItemSwapper#119]
its as simple as that, if there was a config option that made it so you couldn't move like you were in the inventory I feel like it would seem a lot less cheaty.

**Comment by tr7zw** [comment]
Was added in the dev builds.

**Comment by JustCauseWhyNot** [comment]
Was an option to change the behavior to revert no movement while in use? Because currently I can't find one. It's also a huge pain not being able to move while in use.

**Comment by tr7zw** [comment]
Seems I misread the question and confused it with the "Unlock Mouse For Lists" settings.

**Comment by JustCauseWhyNot** [comment]
Apparently you can still move with the swap menu opened. But you've got to repress the movement key after opening the menu, and in toggle mode you've got to constantly repress movement key after jumping, changing toolbar spot, or a lot of other things. I find it's like having 2 key roll over where you can only press 1 key at a time.

**Comment by tr7zw** [comment]
Sounds more like you have some mod conflict. Thats not the correct behavior. "repress" already makes no sense, since letting go just closes the UI.

**Comment by JustCauseWhyNot** [comment]
> "repress" already makes no sense, since letting go just closes the UI.

Not with toggle mode.

**Comment by tr7zw** [comment]
See my comment on the other issue. Toggle mode is for controller users/people that have issues pressing multiple buttons, not really for keyboard and mouse users.

**Comment by JustCauseWhyNot** [comment]
Are you able to move while holding down the R key? Because when the menu is open regardless of having toggle mode or not movement is stopped immediately without and you can't move unless re-pressing movement key. It just feels off for whats supposed to be a item quick swap.

**Comment by tr7zw** [comment]
Yes you can. That's why this issue is about an option to turn that OFF, which is your issue.

**Comment by JustCauseWhyNot** [comment]
> It's unusable in non toggle mode

I don't agree.

> and you can't just see the numbers/all entries

That's very valid. Not something I thought of while using this mod for a short minute. I didn't run into that use case yet.

**Comment by tr7zw** [comment]
> That's very valid. Not something I thought of while using this mod for a short minute. I didn't run into that use case yet.

Any 6+ shulkers, tools, banners, heads, potions, food etc will cause that.

> It's unusable in non toggle mode

While holding R you can at best reach 1-5. But for that you need to let go of wasd, which is just making it harder to use.

**Comment by TheDerpu0ne** [comment]
so uhh, your opinions on my suggestion? I keep getting unrelated notifications haha

**Comment by tr7zw** [comment]
Yea sorry about that. As I stated, apparently misread the original question, so now it's back open and on the todo. But will be a bit tricky to do, especially with 1.20. Since the R keybind needs to be passed, by wasd somehow blocked.

**Comment by TheDerpu0ne** [comment]
Thanks, don't worry I can wait :) take ur time
