### ISSUE TITLE
[BUG] It lags the game and freezes for half a second

### ISSUE THREAD

**Issue by EGOIST1372** [tr7zw/ItemSwapper#128]
### Version information

v0.3.2-1.19.3

### Other relevant installed mods

fabricloader: Fabric Loader 0.14.12 		fallingleaves: Falling Leaves 1.14.3+1.19.3 		fancymenu: FancyMenu 2.13.2 		fastopenlinksandfolders: FastOpenResourcePacks 1.1.1 		ferritecore: FerriteCore 5.1.0 		fmextension_audio: FancyMenu Audio Extension 1.1.1 		forgeconfigapiport: Forge Config API Port 5.0.6 			com_electronwill_night-config_core: core 3.6.5 			com_electronwill_night-config_toml: toml 3.6.5 		fpsdisplay: FPS-Display 1.5.0+1.19 		freecam: Freecam 1.1.8+1.19 		image2map: Image2Map 0.4.0 			map-canvas-api: Map Canvas API 0.2.1+1.19.3 			sgui: sgui 1.2.0+1.19.3 		immediatelyfast: ImmediatelyFast 1.1.6 			com_github_llamalad7_mixinextras: MixinExtras 0.1.1 		impactfulweather: Biome Particle Weather 4.0.4 		indium: Indium 1.0.12+mc1.19.3 		inventoryhud: Inventory HUD + 3.4.7 		iris: Iris 1.5.1 			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8 			org_anarres_jcpp: jcpp 1.4.14 			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1 		itemswapper: ItemSwapper 0.3.2-mc1.19.3 		java: OpenJDK 64-Bit Server VM 17 		keepheadnames: Keep Head Names 1.5.1 		konkrete: Konkrete 1.6.0 		krypton: Krypton 0.2.1 			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT 		lazydfu: LazyDFU 0.1.3 		lightoverlay: Light Overlay 7.0.2 		lithium: Lithium 0.10.4 		loadmyresources: Load My Resources 1.0.4 		malilib: MaLiLib 0.14.0 		memoryleakfix: memory Leak Fix 1.19.3-0.7.0 		microdurability: microDurability 0.3.6+1.19 			microdurability-core: microDurability Core 0.3.6 		midnightlib: MidnightLib 1.1.0 		minecraft: Minecraft 1.19.3 		minihud: MiniHUD 0.25.0 		mixintrace: MixinTrace 1.1.1+1.17 		modmenu: Mod Menu 5.0.2 		multibeds: MultiBeds 1.3.3 		nicephore: Nicephore fabric-1.19.x-1.0.0 			com_profesorfalken_jpowershell: jPowerShell 3.1.1 		notenoughanimations: NotEnoughAnimations 1.6.2 		onsoulfire: On Soul Fire 1.19-3 			cardinal-components-base: Cardinal Components API (base) 5.1.0 			cardinal-components-entity: Cardinal Components API (entities) 5.1.0 		owo: oωo 0.9.3+1.19.3 			blue_endless_jankson: jankson 1.2.1 		phosphor: Phosphor 0.8.1 		presencefootsteps: Presence Footsteps 1.7.1 			kirin: Kirin UI 1.13.2 		puzzle: Puzzle 1.4.2-1.19.3 			puzzle-base: Puzzle Base 1.4.2-1.19.3 			puzzle-gui: Puzzle GUI 1.4.2-1.19.3 			puzzle-models: Puzzle Models 1.4.2-1.19.3 			puzzle-splashscreen: Puzzle Splash Screen 1.4.2-1.19.3 		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67 		replaymod: Replay Mod 1.19.3-2.6.10 		replayvoicechat: Replay Voice Chat 1.19.3-1.2.4 		roughlyenoughitems: Roughly Enough Items 10.0.581 			error_notifier: Error Notifier 1.0.9 		satin: Satin 1.10.0 		screenshotclipboard: Screenshot to Clipboard 1.0.9 		searchlight: Searchlight 1.1.9 		shetiphiancore: ShetiPhianCore 1.3.5 		showmeyourskin: Show Me Your Skin! 1.3.7+1.19.3 			cicada: CICADA 0.1.1 				langfiles-plus: Langfiles Plus 1.0.0 		shulkerboxtooltip: Shulker Box Tooltip 3.2.4+1.19.3 		silence: Silence 1.19.3-fabric0.68.1-1.0.1 			crowdin-translate: CrowdinTranslate 1.4+1.19.3 			gbfabrictools: GBfabrictools 1.3.4+1.19.3 		skinlayers: 3d Skin Layers 1.5.2-mc1.19.3 		smoothboot: Smooth Boot 1.19-1.7.1 		sodium: Sodium 0.4.8+build.22 		sodium-extra: Sodium Extra 0.4.16+mc1.19.3-build.91 			caffeineconfig: CaffeineConfig 1.0.0+1.17 		sound_physics_remastered: Sound Physics Remastered 1.19.3-1.0.18 		status: Status 1.19.3-1.0.0 		status-effect-bars: Status Effect Bars 1.0.2 		stendhal: Stendhal 1.3.4-1.19.3 			libgui: LibGui 6.5.0+1.19.3 				jankson: Jankson 5.0.0+j1.2.1 				libninepatch: LibNinePatch 1.1.0 		vcinteraction: Voice Chat Interaction 1.19.3-1.0.3 			polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.3.0-rc.3+1.19.3 		voicechat: Simple Voice Chat 1.19.3-2.3.26 		waveycapes: WaveyCapes 1.2.2 		wi_zoom: WI Zoom 1.4-MC1.19.3 		windchimes: Windchimes 1.2.2

### Expected Behavior

it should work without lag and freeze

### Actual Behavior

when I open the item swapper for any item game lags and freeze for half a second
At first I thought it might be [exordium](https://www.curseforge.com/minecraft/mc-mods/exordium) mod, the I removed it and still issue exists then I thought it might be [immediatelyfast](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast) mod and yet it wasn't either and then I thought it might be [blur](https://www.curseforge.com/minecraft/mc-mods/blur-fabric) mod, obviously wasn't
here is the showcase video :
https://streamable.com/8xunpm

### Reproduction Steps

use my mods that I listed then boom you got an issue 

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

**Comment by tr7zw** [comment]
That's really weird. Give it a try with the latest dev build from the actions tab, the current release is missing a lot of changes.

**Comment by EGOIST1372** [comment]
@tr7zw  you mean this one?
![image](https://user-images.githubusercontent.com/86555131/212446119-227877ea-3869-42b9-ad66-6294fd388cc4.png)

cause I tested it and resource pack won't load and say fail to reload resource pack

**Comment by tr7zw** [comment]
Yea that one. Send the error. Are you using some custom resource pack?

**Comment by tr7zw** [comment]
Also make sure to use the jar without -all or -source on it.

**Comment by tr7zw** [comment]
Ah just noticed from the above mods, you're on 1.19.3. Then I'll just keep this issue for now, till the next update is done and gets ported to 1.19.3. I assume something is unhappy about the usage of Overlay instead of Screen, which is fixed in the dev branch(also caused funky issues with Optifine).

**Comment by EGOIST1372** [comment]
yeah I know
I used the right one but it doesn't load the resource pack
and yes I use a bunch of resource packs and after first time it failed to reload resource pack it unloaded all of my resource packs and now I have to select them all again :|
![image](https://user-images.githubusercontent.com/86555131/212446273-42da7ca7-3338-42ad-b490-52a7b3db125d.png)
![image](https://user-images.githubusercontent.com/86555131/212446335-26daf4e8-d01f-4712-a291-e891207f7444.png)

**Comment by tr7zw** [comment]
Honestly, on 1.19.3 this thing shouldn't even boot and crash at any moment it can.

**Comment by EGOIST1372** [comment]
I was shocked too cause the name was saying 1.19.2 but since you said test it I thought it is compatible to that as well lol

**Comment by tr7zw** [comment]
I forgot that I had released a 1.19.3 version/that dev was still on 1.19.2. The main change between 1.19.2 and 1.19.3 is how it resolves the resource pack values to the actual items. That the game launched at all is kinda amazing, but the resource pack processing correctly failed.

**Comment by EGOIST1372** [comment]
I leave this image here for better visual of my current mods. obviously these are not all of them since many of my mods not updated to 1.19.3 yet
![image](https://user-images.githubusercontent.com/86555131/212446605-f9d3d6c6-bd6c-4813-bd62-03652a772450.png)

**Comment by tr7zw** [comment]
Let me quickly try creating a 1.19.3 dev build based on the 1.19.2 version.

**Comment by tr7zw** [comment]
Pushed to the 1.19.3 branch all changes, give it time to build, and then test with that version. It's 3:40am now, I'm off to bed.

**Comment by EGOIST1372** [comment]
6 AM here as well. I needed to go to bed hours ago :D
I try and then if I didn't pass out I will reveal the results

**Comment by EGOIST1372** [comment]
I tested and the bug is gone and everything is silky smooth
thanks for fast response
I really love this mod

**Comment by tr7zw** [comment]
Neat. You might notice some wip stuff like the putting away button, new settings and other slight changes. Just keep in mind that this is an in progress dev build.
