### ISSUE TITLE
Fix texture alignment

### ISSUE THREAD

**Issue by ViTulyankin** [tr7zw/ItemSwapper#13]
I know, I sound like "Everything was better back in days", but... The old ones are really better, in my opinion
![image](https://user-images.githubusercontent.com/92220631/205251089-35a2271d-8b91-481e-96c0-92df32c54499.png)

Also, new textures are misaligned
![Без имени](https://user-images.githubusercontent.com/92220631/205252226-61eb8eae-9f88-4717-8603-5dd37744d7b7.png)

**Comment by tr7zw** [comment]
We are aware of the misalignment issue, which will be fixed later. And no, for now, the old textures won't be accessible(they just don't work for the bigger grids, since they are a lot bigger per item).
