### ISSUE TITLE
Use Item Tags in Default Resource Pack

### ISSUE THREAD

**Issue by Avakining** [tr7zw/ItemSwapper#130]
### Is your feature request related to a problem?

Modded tools, weapons, and blocks aren't available by default in the switcher.

### Describe the solution you'd like

Using tags (such as #c:swords, #c:tools, #c:pickaxes, or #minecraft:logs) in the default resource pack instead of specific item IDs

### Describe alternatives you've considered

The best alternative would be to manually add support for every modded weapon, tool, and block which would take a lot of labour.

### Additional context

[This site](https://fabricmc.net/wiki/tutorial:tags) defines how to use tags in Fabric mods, though it should be easier to use them without defining them

**Comment by tr7zw** [comment]
Item tags can not be used for this mod. Tags are server-side, and therefore not usable for this clientside logic. Added to that, by default, tags are so incomplete and unordered, that they are not useful at all.
> The best alternative would be to manually add support for every modded weapon, tool, and block which would take a lot of labour.

The reworked resource pack format will have a solution for this, not using tags.
