### ISSUE TITLE
[BUG] Vivecraft odd bugs

### ISSUE THREAD

**Issue by Goober19** [tr7zw/ItemSwapper#131]
### Version information

itemswapper-fabric-0.3.2-mc1.19.3

### Other relevant installed mods

vivecraft-1.19.3-0.0.14-a2-fabric.jar

### Expected Behavior

be able to select and switch to items

### Actual Behavior

the menu would show up, but no item would be highlighted, and no selection could be made

### Reproduction Steps

1. assign a keybind to itemswapper in steamvr controls
2. press the keybind
3. game becomes paused (i let vivecraft know about the pausing part) and no selection can be made
4. sad

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

I do want to put it out there that I dont expect a fix asap, just want information to be available if there is a time youd like to debug.
Also for whatever reason either a certain number of mods, or a certain combination of mods makes itemswapper sort of work? i tried troubleshooting but after a few hours and no mods making a real difference by themselves I gave up. it works enough for me :D
working log:[2023-01-19-6.log.gz](https://github.com/tr7zw/ItemSwapper/files/10462971/2023-01-19-6.log.gz)
not working log: [2023-01-19-7.log.gz](https://github.com/tr7zw/ItemSwapper/files/10462981/2023-01-19-7.log.gz)

**Comment by tr7zw** [comment]
Vivecraft is part of the next release thanks to @MelonCode
