### ISSUE TITLE
[BUG] inventorio- tabs get pushed to the side

### ISSUE THREAD

**Issue by DanMeadWasTaken** [tr7zw/ItemSwapper#133]
### Version information

0.9.0-beta-1.19.x

### Other relevant installed mods

inventorio

### Expected Behavior

the tabs to be centered properly

### Actual Behavior

The tabs are pushed off oddly

### Reproduction Steps

load up with inventorio and inventory tabs present and switch to the inventorio screen

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

![image](https://user-images.githubusercontent.com/75497984/216308783-20ed5a24-4fd1-4dc4-bcf7-f46ad21a99df.png)

**Comment by tr7zw** [comment]
This mod doesn't touch any screens. Are you sure this is related to this mod?

**Comment by DanMeadWasTaken** [comment]
I'm so sorry, i got turned around while tryna make a report to inventory profiles next, and was tryna delete it before it got noticed but my internet is acting up
