### ISSUE TITLE
Broken implementation of ModMenuApi

### ISSUE THREAD

**Issue by UchiWerfer** [tr7zw/ItemSwapper#140]
Trying to run the Item-swapper mod version 0.3.2 using Minecraft 1.19.4, Fabric launcher version 0.14.18, Fabric-API version 0.76.0 and both Mod-menu versions 5.0.2 and 6.1.0 release candidate 4 causes error found in attached log-file.
[latest.log](https://github.com/tr7zw/ItemSwapper/files/11113950/latest.log)

**Comment by tr7zw** [comment]
0.3.2 is for 1.19.3, not 1.19.4. If you want to use the dev build 0.4.0 for 1.19.4, use the Actions tab above.
