### ISSUE TITLE
[CRASH] Trying to open an empty Shulker crashes the game

### ISSUE THREAD

**Issue by drgndck** [tr7zw/ItemSwapper#143]
### Version information

itemswapper-fabric-0.4.0-mc1.19.4

### Other mods installed

3d Skin Layers(v1.5.3-mc1.19.4), Ambient Sounds(v5.2.18), Amplified Nether(v1.2.1a), Anvil Restoration(v2.0), Architectury(v8.1.75), Areas(v4.3), Armor Chroma(v1.2.5), AttributeFix(v19.0.1), Auth Me(v6.0.0), Auto AFK Fisher(v1.1.0+build.0), Auto Attack(v1.3.3), AutoSwitch(v6.0.2), AutoSwitch API(v3.0.0), Balm(v6.0.2), Bendy api(v4.0.0), Better Runtime Resource Pack(v0.9.0), Better Statistics Screen(v2.5.2+1.19.4), BetterCommandBlockUI(v0.3.1), BetterSafeBed(v4), Bobby(v4.0.5), Bookshelf(v18.0.2), Borderless Mining(v1.1.7+1.19.4), Bossbar stack(v1.0.1), Bridging Mod(v1.19.4-v1.3.0), CICADA(v0.3.0), CIT Resewn: Defaults(v1.1.3+1.19.4), Campfire Spawn and Tweaks(v3.4), Capes(v1.5.2+1.19.3), Cardinal Components API(v5.1.0), Carpet TIS Addition(v1.46.1), CarrotConfig(v1.0.0+1.19.3), Chat Patches(v194.3.0), ChoiceTheorem's Overhauled Villages(v3.1.8), Chunks Fade In(v1.0.1-1.19.4), Chunky(v1.3.53), Clean F3(v0.2.2), Client Tweaks(v10.0.1), Cloth Config v10(v10.0.96), Cloud(v1.8.3), Continuity(v3.0.0-beta.2+1.19.3), CrackerUtil(v0.2.4-1.19.4), CreativeCore(v2.10.7), CrowdinTranslate(v1.4+1.19.3), DamageVignette(v1.1.4), DarkPaintings(v15.0.1), DashLoader(v5.0.0-alpha.13+1.19.4), Dawn API(v4.2.0), DeathLog(v0.3.2+1.19.4), Debugify(v1.19.4+1.0), Disable Custom Worlds Advice(v4.0), Discerning Furnace(v1.0.10), Display Case Mod(v1.0.4), Draggable Resource Packs(v3.0.1+build.9), Drip Sounds(v1.19-0.3.2), Dynamic Crosshair(v5.3+1.19.4), Dynamic FPS(v2.2.0), Dynamic Sound Filters(v1.4.0+1.19.4), Ears(v1.4.6), Eating Animation(v1.9.3), Emotecraft(v2.2.7-b.build.48), Enchantment Lore(v1.3.1), Entity Model Features(v0.2.4), Entity Texture Features(v4.3.5), EntityCulling-Fabric(v1.6.2-mc1.19.4), Error Notifier(v1.0.9), FPS Reducer(v1.19.4-2.3), Fabwork(v1.1.9), Falling Leaves(v1.15.0+1.19.4), FastQuit(v2.1.0+1.19.3), FerriteCore(v5.2.0), FirstpersonModel(v2.2.3), Fix Book Gui Mod(v1.2), Forge Config API Port(v6.0.2), Freecam(v1.1.9+1.19), FullGrownCropMarker(v1.19.4-1.2.0), GMod Title Screen(v1.2+1.19.4), Game Menu Remove GFARB(v2.1.0), Globalization(v1.1.0), Glowing Torchflower(v1.0.0), GoogleChat(v0.6.2), Grindstone Sharper Tools(v3.1), Hat List(v1.4), Healing Campfire(v5.1), Held Item Info(v1.4.2), Highlight(v1.2.0), Hyphen(v0.4.0-rc.3), Immersive Thunder(v1.19.4+1.1.2), Incendium(v5.2.1), Indicatia(v7.2.0), Indium(v1.0.15+mc1.19.4), Infinite Trading(v4.0), Inspecio(v1.8.0+1.19.4), Interactic(v0.2.0+1.19.4), InvMove(v0.8.3), Inventory Essentials(v7.0.1), Inventory HUD +(v3.4.11), Inventory Profiles Next(v1.9.5), Iris(v1.5.2), Isometric Renders(v0.4.4+1.19.4), ItemSwapper(v0.4.0-mc1.19.4), Jade(v10.0.0), Java-WebSocket(v1.5.2), Kirin UI(v1.14.0), LambDynamicLights(v2.3.0+1.19.4), LambdaBetterGrass(v1.5.0+1.19.4), Langfiles Plus(v1.0.0), LibJF Base(v3.7.1), Load My Resources(v1.0.4), MAmbience(v5.3.0+1.19.4), MCChatGPT(v0.2.0), Make Bubbles Pop Mod(v0.1.1-1.19.4), MaxHealthFix(v10.0.1), Memory Leak Fix(v1.0.0), MidnightLib(v1.2.1), MixinExtras(v0.2.0-beta.6), Mod Menu(v6.1.0-rc.4), Mod-erate Loading Screen(v1.2.1+1.19.4), Model Gap Fix(v1.10), Modflared(v0.1.2-1.19.4), Mods Command(v1.1.2), More Culling(v1.19.4-0.17.0), MoreMcmeta(v1.19.4-3.0.6), Mouse Tweaks(v2.24), Music Notification(v1.1), Not Enough Crashes(v4.4.0+1.19.4), Noxesium(v0.1.8), Ok Boomer(v0.1.2+1.19.4), OpenJDK 64-Bit Server VM(v17), Organizable Play Screens(v1.1.3), Packet Logger(v1.4.0), Paginated Advancements(v2.0.0-1.19.4), Paladin's Furniture(v1.1.3), PaperDoll(v1.1.1-mc1.19.4), Peek(v1.19.4-1.0.5), Physics Mod(v2.11.11), Player Animator(v1.0.2+1.19.4), Pride Lib(v1.2.0+1.19.4), Quilt Kotlin Libraries: Core(v2.0.1), Quilt Multipart Entity API(v5.0.0-beta.1+1.19.4), Quilted Fabric API Base(v6.0.0-beta.2+0.76.0-1.19.4), Random Village Names(v3.2), Recipe Book Is Pain(v0.9.0-1.19.4), Recursive Resources(v2.3.0+1.19.4), Reese's Sodium Options(v1.5.0+mc1.19.4-build.72), Reflect(v1.1.0), Resourceful Lib(v1.3.0), Roughly Enough Items(v11.0.597), Roughly Enough Professions(v1.2.1), Roughly Enough Resources(v2.8.0), Selective Entity Removal(v2.2.0), Server Pack Unlocker(v1.3), Server Resource Pack Checker(v1.19.4-1.0.1), Shared Resources(v1.5.0), Shared Resources API(v1.5.0), Simple Fog Control(v1.3.1), Simply No Shading(v6.0.5+1.19.4), Sit(v1.19.4-23), Smooth Boot(v1.19.4-1.7.0), Smooth Swapping(v0.8), Sneaky!(v1.2), Sodium(v0.4.10+build.24), Sodium Extra(v0.4.18+mc1.19.4-build.100), SpruceUI(v4.2.0+1.19.4), Starlight(v1.1.1+fabric.ae22326), Status Effect Bars(v1.0.2), Stitch(v1.0.0), Suggestion Tweaker(v1.19.1-1.3.1), TCD Commons API(v2.5.1+1.19.4), Taski(v2.1.0), TieFix(v1.13.0), Tiny Item Animations(v1.19.4-1.0), Tips(v10.0.2), Toggleable Item Frames(v2.1.1-1.19.x), Traveler's Titles(v1.19.4-Fabric-3.3.0), TravellersToasts(v1.1.0+1.19.4), Trinkets(v3.6.0), Universal Ores(v1.5.1), Vanilla Notebook(v2.2.0), Vanity Slots(v1.2.7), Very Many Players(v0.2.0+beta.7.69), ViaFabric(v0.4.9+29-main), ViaFabric for 1.19(v0.4.9+29-main), Visible Barriers(v2.0.1), Visuality(v0.7.0), Void Fog(v2.9.0), WaveyCapes(v1.3.2), Weaker Spiderwebs(v3.2), What's That Slot?(v1.3.3+1.19.4), Worldmesher(v0.3.0+1.19.3), Xaero's World Map(v1.29.5), YUNG's API(v1.19.4-Fabric-3.10.1), YetAnotherConfigLib(v2.3.1), adapter-rxjava2(v2.9.0), geantyref(v1.3.13), mapping-io(v0.3.0), reactive-streams(v1.0.3), toml(v3.6.5)

### Reproduction Steps

1. Have an empty Shulker in your inv
2. Open ItemSwapper
3. Try to open the empty shulker (right-clicking the shulker)

### Crash Report file

[crash-2023-04-12_04.40.37-client.txt](https://github.com/tr7zw/ItemSwapper/files/11206584/crash-2023-04-12_04.40.37-client.txt)

### Additional information

https://user-images.githubusercontent.com/41470551/231335953-3d67361c-5b75-413d-99c5-fcb915acd5c0.mp4

🤗

**Comment by AdvancedWipe** [comment]
From your crash report, I can see that you are using Quilt. Keep in mind that this mod does not officially support Quilt yet. 

I tried to recreate the issue you are reporting but for me, it is not crashing the game.

**Comment by tr7zw** [comment]
I only checked the stacktrace, and it did point into the code. Thats why I reopened the issue.
