### ISSUE TITLE
Hand restock 

### ISSUE THREAD

**Issue by IMT07** [tr7zw/ItemSwapper#144]
### Is your feature request related to a problem?

well, if you have an item in your hand and a full shulkerbox with that item in your inventory, you will run out eventually and you'll have to place the box and pick another stack 

### Describe the solution you'd like

when you run out of blocks, restock the hand with items from the shulkerbox in your inventory, or maybe if you got only 5 items left in your hand.

**Comment by tr7zw** [comment]
Click the restock button or the last item button or use the UI to open the shulker and grab the item.
