### ISSUE TITLE
[Incompatibility] Incompatible with Optifine + Optifabric

### ISSUE THREAD

**Issue by ReiaTheGeia** [tr7zw/ItemSwapper#15]
When launching with current versions of Optifabric and Optifine the whole thing locks up doing nothing.

**Comment by ReiaTheGeia** [comment]
Wait nevermind it worked this time

**Comment by tr7zw** [comment]
Huh was just setting up a test environment. I'll be honest, I don't use Optifine at all, so it's possible that there are issues with it.

**Comment by ReiaTheGeia** [comment]
The actual issue might actually be cloth config,

**Comment by ReiaTheGeia** [comment]
nevermind it isn't lol. I'm just bad at being up to date
