### ISSUE TITLE
[BUG] Mouse speed setting does not apply

### ISSUE THREAD

**Issue by Excederus** [tr7zw/ItemSwapper#153]
### Version information

itemswapper-fabric-0.4.0-mc1.20

### Other relevant installed mods

modmenu-7.0.1

### Expected Behavior

Changing the mouse speed inside settings actually applies

### Actual Behavior

When clicking done and re-entering the config screen the mouse speed change is not applied and resets back to default

### Reproduction Steps

1. Open the config
2. Change the mouse speed
3. Click done
4. Open the config again
5. See it revert back to default

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

**Comment by tr7zw** [comment]
It sounds like you had the config file locked or something. Works just fine.
