### ISSUE TITLE
Shulker with no data causes crash

### ISSUE THREAD

**Issue by MagmaBro123** [tr7zw/ItemSwapper#155]
### Version information

itemswapper-fabric-0.4.0-mc1.20

### Other mods installed

![image](https://github.com/tr7zw/ItemSwapper/assets/51277766/191f50fa-5a46-449d-ad78-d4156622ac22)

### Reproduction Steps

Try inserting an item via ItemSwapper's UI into a shulkerbox.

### Crash Report file

[crash-2023-06-26_23.27.23-client.txt](https://github.com/tr7zw/ItemSwapper/files/11878095/crash-2023-06-26_23.27.23-client.txt)

### Additional information

I'm not sure if this issue is caused by the plugin being outdated or something.

**Comment by tr7zw** [comment]
This has nothing to do with the plugin. Somehow the mod failed to grab the shulker data at all(got a size 0 inventory), maybe that shulker was never placed(so it has no data) and I forgot to catch that?

**Comment by MagmaBro123** [comment]
Well, everything's up-to-date.

**Comment by tr7zw** [comment]
Again, nothing to do with the server/plugin.
