### ISSUE TITLE
[BUG] Mouse buttons do not work held down

### ISSUE THREAD

**Issue by imsofi** [tr7zw/ItemSwapper#158]
### Version information

itemswapper-fabric-0.4.0-mc1.19.4

### Expected Behavior

Holding down a button on the mouse (like `Mouse Button 4`) will open the itemswapper gui normally while pressed down.

### Actual Behavior

The GUI will quickly open and close as if i only clicked the button instead it being held down. Using the "Toggle key" in the configuration helps, but subsequent clicks of `Mouse Button 4` will now not close the GUI, and you need to use left click to select an item to close it out.

### Reproduction Steps

1. Go into the keybinds of minecraft.
2. Set ItemSwapper key to a mouse button, like a side button (Mouse Button 4 was what i used).
3. Try to open the interface with both the "Toggle" setting turned off and on.

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

Game is ran on Linux with Xorg.

**Comment by tr7zw** [comment]
Duplicate #40
