### ISSUE TITLE
Cursor is too fast inside the palette

### ISSUE THREAD

**Issue by egeesin** [tr7zw/ItemSwapper#16]
I'm not sure what's the intended cursor speed inside the empty inventory palette but it feels too fast comparing to normal inventory menu. Not really an issue while browsing around 8 or lesser slots among the copper block variants for ex., but it's getting harder to choose accurately on bigger palettes like wood variants or whole inventory palette.

Is there a way to adjust default cursor speed that it matches to in-game cursor speed + adding an option to set cursor speed? Also want to say that I really appreciate the development and idea of this mod, hope it gets more attention to the community and to the Mojang devs hopefully.

**Comment by Mr3DAlien** [comment]
I personally would prefer if there was an option to no longer be able to move while the blocks selector is on and instead have my mouse show up to better select those blocks. I think in most cases there is no real use to move while selecting the block you want. I think it currently is a real pain to select any blocks.

**Comment by tr7zw** [comment]
Not allowing movement would cause complications while building, and is not multiplayer-friendly.

**Comment by Mr3DAlien** [comment]
Okay makes sense, it still would be cool if my normal cursor would show up to select the icons. Currently it is to hard to select anything in bigger categorys and it is way quicker to manually take the items out of your inventory, which of course defeats the point of the mod. It takes me far to long to select the item in the middle of the gui.

**Comment by tr7zw** [comment]
You can enable a cursor in the settings.

**Comment by SebSemos** [comment]
Cursor Speed is actually binded to the ingame cursor setting. A separate control will be very welcome when you play in hyperspeeeeed lol

**Comment by Mr3DAlien** [comment]
I think it doesn't, when I enable the mouse cursor it is definitly way faster than my normal cursor is. I also am not that big of a fan of the whole Minecraft reticle that used locked into the gui. I think it would be way better to just use the windows cursor to select those items.

**Comment by tr7zw** [comment]
Using the windows cursor is not possible. So I have to simulate a cursor, and since I get the movement from the movement handler, it's possible that the ingame mouse setting gets applied. I will have to look into how I can ignore it/revert it/apply my own modifier to it.
