### ISSUE TITLE
[BUG] Panel flashes quickly, then disappeares

### ISSUE THREAD

**Issue by henry-von-wichert** [tr7zw/ItemSwapper#161]
### Version information

itemswapper-fabric-0.4.0-mc1.20

### Expected Behavior

The item swapper panel should open and stay open for as long as the key is held.

### Actual Behavior

The panel flashes quickly, then disappears.

### Reproduction Steps

I'm playing on fabric 0.14.21. When I press the hotkey for opening the panel, it just quickly flashes. When I use toggle mode it toggles as intended. The issue still happens without any other mods.

### Render engine

- [X] Vanilla
- [ ] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

**Comment by tr7zw** [comment]
Sounds like you bound it to the mouse maybe?

**Comment by henry-von-wichert** [comment]
I've tried to bind it to several different keys (currently left option on a MacBook) and it always had the same issue.

**Comment by tr7zw** [comment]
Hm, might be an issue on mac like when trying to bind it to a mouse on Windows. Basically for all mc know the button gets pressed once and then not anymore while the UI is open.

**Comment by henry-von-wichert** [comment]
I haven't had any problems with other mods like Zoom, where you need to press and hold a button.
