### ISSUE TITLE
Add weapons to swapper.

### ISSUE THREAD

**Issue by OctoIJel** [tr7zw/ItemSwapper#162]
### Is your feature request related to a problem?

I'll switch to a tool when I need to break something but then have to manually switch to a sword or bow whenever in combat

### Describe the solution you'd like

allow swapping to any combat-related item instead of just tools

### Additional context

![image](https://github.com/tr7zw/ItemSwapper/assets/111668702/2eb30ecd-fdac-444c-912a-07448e49f846)

![image](https://github.com/tr7zw/ItemSwapper/assets/111668702/ff9ef615-cd9c-4ca8-b63a-0e9ad0d7e3b3)

**Comment by tr7zw** [comment]
Middleclick.
