### ISSUE TITLE
[BUG] The link for the Fabric mod takes me to tr7zw's profile, not this repository

### ISSUE THREAD

**Issue by shane-smith** [tr7zw/ItemSwapper#181]
### Version information

itemswapper-fabric-0.5.3-mc1.20.2

### Other relevant installed mods

MultiMC displays this URL as a clickable link in the mods menu

### Expected Behavior

URL is https://github.com/tr7zw/ItemSwapper

### Actual Behavior

URL is https://github.com/tr7zw

### Reproduction Steps

Clicking this link in the MultiMC mods list for an instance of Minecraft:

![image](https://github.com/tr7zw/ItemSwapper/assets/943942/85339ecb-4eee-4328-bed8-1df006ff54ca)

### Render engine

- [ ] Vanilla
- [ ] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

MultiMC seems to be reading from the "homepage" attribute in `fabric.mod.json`

![image](https://github.com/tr7zw/ItemSwapper/assets/943942/7bed0737-c238-4933-a119-08e7b87b968d)

If I manually update that URL in the archive to match the "sources" attribute, the URL in MultiMC now takes me directly to the repository for this mod.

Because every other mod that I have installed takes me to either the GitHub repository, the Modrinth page, or the CurseForge page ... all of which are places that I can download the most recent version of that mod ... ItemSwapper is the odd one out here.

I usually use this link after every Minecraft version update to jump to the download pages for all of the mods that I'm updating 🙂

**Comment by tr7zw** [comment]
Huh, never knew that anything besides Modmenu would read these lines. I'll point homepage to https://modrinth.com/plugin/itemswapper since sources has its own line for the Github link.

**Comment by shane-smith** [comment]
Sure, that works too. Thank you!
