### ISSUE TITLE
[BUG] Objects are not extracted from the shulker box

### ISSUE THREAD

**Issue by Bastardxs** [tr7zw/ItemSwapper#182]
### Version information

itemswapper-fabric-0.5.3-mc1.20.2

### Expected Behavior

The item should be swapped to the hotbar

### Actual Behavior

The mod menu opens and the related items are shown, but if these are in a shulker box they do not allow them to be extracted

### Reproduction Steps

-Press item to be extracted
-Nothing happens

### Render engine

- [X] Vanilla
- [ ] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

Im playing in singleplayer, It is the only mod installed along with the fabric api and tried to create different worlds and the same thing happens in all of them.

**Comment by tr7zw** [comment]
Did you maybe turn them off in the config UI/config file?

**Comment by Bastardxs** [comment]
"configVersion": 1,
  "showTooltips": true,
  "toggleMode": false,
  "showCursor": true,
  "serverPreventModUsage": false,
  "editMode": false,
  "creativeCheatMode": true,
  "ignoreHotbar": true,
  "unlockListMouse": false,
  "disableShulkers": false,
  "controllerSpeed": 8.0,
  "mouseSpeed": 1.0,
  "fallbackInventory": true,
  "vivecraftCompat": true,
  "allowWalkingWithUI": true,
  "startOnItem": false

This is my current config

**Comment by tr7zw** [comment]
Ah crap, could be that something went wrong due to 1.20.2's message channel changes.
