### ISSUE TITLE
Search Bundles as well as shulker boxes

### ISSUE THREAD

**Issue by FrosteByte** [tr7zw/ItemSwapper#186]
### Is your feature request related to a problem?

Shulker boxes are ironically more accessible than bundles since items stored in bundles don't show up in the mod lists.

### Describe the solution you'd like

When pressing the itemswapper hotkey, search for related items in the inventory, the hotbar (if enabled), shulker boxes (if enabled), and bundles (if enabled). Add an option in the mod config like the one for enabling the search of shulker boxes, but for bundles. The two options should be independent of each other.

**Comment by tr7zw** [comment]
Bundles are not that doable with the mod. When having an item in hand, it can't be swapped with an item in a bundle since that would potentially cause invalid bundle fillings. No real support for bundles is planned for now, as even Mojang doesn't yet fully know how they should work.
