### ISSUE TITLE
[CRASH] crashed with fapi 0.91.0 and above

### ISSUE THREAD

**Issue by liangmoe** [tr7zw/ItemSwapper#187]
### Version information

itemswapper-fabric-0.5.4-mc1.20.2

### Other mods installed

fabric-api-0.91.1+1.20.2

### Reproduction Steps

install fapi 0.91.0 or 0.91.1 and crashed, need to downgrade it to 0.90.7 to prevent the issue

### Crash Report file

only latest log
[2023-11-28-2.log](https://github.com/tr7zw/ItemSwapper/files/13480057/2023-11-28-2.log)

**Comment by HyPeRXKo** [comment]
I also have this issue, and the workaround work for me too.

**Comment by tr7zw** [comment]
Known issue, will take some time to rework the network logic to get it running on the latest fabric api.
