### ISSUE TITLE
Option to add the hotbar in the 'Inventory' screen.

### ISSUE THREAD

**Issue by AstudilloMarillo** [tr7zw/ItemSwapper#191]
### Is your feature request related to a problem?

I want an easy and fast way to swap items around in my hotbar while being able to keep moving.

### Describe the solution you'd like

What I'd like is an option to add the hotbar to ItemSwapper's Inventory screen. That way, you can press the Inventory hotkey and use the mouse to swap your currently selected hotbar item slot with a different hotbar item slot without ever stopping your movement.

I think having the hotbar would also be quite intuitive/familiar to see on ItemSwapper's Inventory screen, since it's also present on the regular inventory screen. Of course, this should be a toggleable option so people who don't like it can leave it off.

### Describe alternatives you've considered

You can kinda achieve the same using your offhand, but to me that's just not intuitive, and I can't get the hang of it.

**Comment by tr7zw** [comment]
But whats the point to on the fly reorder the hotbar items using hotkeys... when the hotkey also normally just selects the slot? You'd have to either use an empty slot or click through the UI to get to the inventory view and then hotkey? That doesn't like a good idea.

**Comment by AstudilloMarillo** [comment]
> But whats the point to on the fly reorder the hotbar items using hotkeys... when the hotkey also normally just selects the slot? You'd have to either use an empty slot or click through the UI to get to the inventory view and then hotkey? That doesn't like a good idea.

So, here's an example I'm thinking about:

I'm running away from mobs in the nighttime and I notice my sword is not in the number 1 spot where I'd like it, right now it's in the number 3 spot. I know that when I eventually have to fight these mobs, I'm going to press 1 out of muscle memory because that's where I like to keep my weapon. I don't want to stop to reorganize my inventory, 'cause mobs may catch up or surprise me. I use the hotkey from ItemSwapper to open the ItemSwapper inventory while my hotbar 1 is selected. I have the hotkey set to non-toggle so it stays open as long as I keep the hotkey pressed. I move my mouse to the 3rd hotbar slot and I let go of the hotkey. Voila, I swapped the hotbar slots 1 and 3 without ever stopping to move and I'm saver now knowing that my muscle memory of pressing 1 will get me my weapon. 

I hope this explanation makes sense and you can at least understand where I'm coming from with this idea.
