### ISSUE TITLE
[BUG] Enderite Tools not working

### ISSUE THREAD

**Issue by TheLittleBoat1401** [tr7zw/ItemSwapper#194]
### Version information

itemswapper-fabric-0.5.5-mc1.20.2

### Other relevant installed mods

enderitemod-1.5.1-1.20.2

### Expected Behavior

When using the hotkey while holding an Enderite Tool, the other tools should show up letting you swap tools (as it happens with vanilla tools)

### Actual Behavior

When using the hotkey while holding the tool, the inventory shows up, meaning it doesn't recognize the tool palette.

### Reproduction Steps

1. Equip an Enderite Tool in your hotbar
2. Have other tools in your inventory
3. Try swapping the tool

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

I saw in videos that there is supposed to be an "Edit Mode", but I don't see it in the settings of the mod to try and add the tools to the palette myself

**Comment by tr7zw** [comment]
You need to make a resource pack for modded items to work. The base mod only contains Vanilla stuff. Check the documentation in the repo for info.

**Comment by TheLittleBoat1401** [comment]
Sorry for my misinformation, what is repo?

**Comment by tr7zw** [comment]
This very thing you opened the issue on^^. The documentation is here: https://github.com/tr7zw/ItemSwapper/tree/1.20.4/docs but it assumes you know the basics of making a resource pack. Another option is look at the "experimental features" addon resource pack that adds the 1.20.5 experimental items: https://github.com/tr7zw/ItemSwapper/tree/1.20.4/Shared/src/main/resources/resourcepacks/experimental_addon .

**Comment by TheLittleBoat1401** [comment]
Thank you!
