### ISSUE TITLE
[BUG] Cursor does not appear, after opening the switch item menu, when using Controlify

### ISSUE THREAD

**Issue by KairuDeibisu** [tr7zw/ItemSwapper#195]
### Version information

V0.5.5

### Other relevant installed mods

Controlify 1.20.4

### Expected Behavior

1. Setup key bind with Controlify.
2. Change item swapper to toggle mode
3. Activating Keybind, the item swapper menu pops up.
4. The item swapper menu stays open.
5. You can pick an item to swap by using the d-pad
6. you can pick an item using the left analog stick.

### Actual Behavior

The item swapper menu stays open, but you are unable to select anything in the menu or navigate it.

### Reproduction Steps

Video to reproduce.
1. Set toggle mode
2. Set keybinding in Controlify
3. use keybinding and try to navigate

https://youtu.be/jf0-SwMdJ3Y

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

There's another controller mod available, but it tends to have more glitches compared to Controlify and is unusable for me. Controlify is built for developers, offering APIs to avoid issues with compatibility issues.

**Comment by tr7zw** [comment]
Didn't you fund the implementation and support of Midnight controls? So there's now Midnight controls, Controlify, and the Vivecraft controller 😵‍💫.

**Comment by KairuDeibisu** [comment]
> Didn't you fund the implementation and support of Midnight controls? So there's now Midnight controls, Controlify, and the Vivecraft controller 😵‍💫.

Yes I'd did 😆. Didn't know about the vive craft controller

**Comment by tr7zw** [comment]
Afaik this is resolved.
