### ISSUE TITLE
[CRASH] Incompatible with JEI

### ISSUE THREAD

**Issue by imagelesskink** [tr7zw/ItemSwapper#196]
### Version information

itemswapper-fabric-0.5.5-mc1.20.4

### Other mods installed

jei-1.20.4-fabric-17.3.0.48

### Reproduction Steps

Go into an inventory and press Shift or Esc and the game crashes if JEI is installed

### Crash Report file

[crash-2024-02-10_17.53.11-client.txt](https://github.com/tr7zw/ItemSwapper/files/14230820/crash-2024-02-10_17.53.11-client.txt)

**Comment by tr7zw** [comment]
> java.lang.NoClassDefFoundError: com/terraformersmc/modmenu/gui/widget/LegacyTexturedButtonWidget
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)

That has nothing to do with this mod, you are missing modmenu for whatever JEI is trying to do.

**Comment by imagelesskink** [comment]
The issue goes away if I uninstall ItemSwapper

**Comment by tr7zw** [comment]
Then you have some other crash. The one you sent is not ItemSwapper.
