### ISSUE TITLE
[BUG] Cursor is invisible in menu even when show cursor is on

### ISSUE THREAD

**Issue by Vannn27** [tr7zw/ItemSwapper#199]
### Version information

itemswapper-fabric-0.4.0-mc1.19.3

### Expected Behavior

The cursor should be visible

### Actual Behavior

The cursor is invisible but I can still select items and click buttons but it's hard to navigate

### Reproduction Steps

1. Press hotkey to open menu
2. Cursor is not visibly seen

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

I use a custom crosshair in vanilla tweaks resource pack if that helps

**Comment by tr7zw** [comment]
1.19.3 vanilla tweaks is missing the cursor texture. Update to a newer version of the game(1.19.3 is dead dead) where this has been fixed.

**Comment by Vannn27** [comment]
after testing, even vanilla crosshair isn't showing. Thanks for clarifying anyway
