### ISSUE TITLE
[FEATURE] Add option to default to inventory instead of palette

### ISSUE THREAD

**Issue by Boden-C** [tr7zw/ItemSwapper#201]
### Is your feature request related to a problem?

Item Swapper would default to the palette in survival even if none of those items are in the inventory. Also, I don't use the palette in survival as my build is already designed in creative and I just need to quick swap with other items in the inventory.

### Describe the solution you'd like

Add an option to always default to inventory and maybe extra options like default to inventory if no available items in the palette

**Comment by tr7zw** [comment]
> default to inventory if no available items in the palette

That already is the default. ("Fallback To Inventory" in the settings)

But yea I guess an option to always open the inventory wouldn't be the worst.

**Comment by Boden-C** [comment]
> That already is the default. ("Fallback To Inventory" in the settings)

If I understand correctly, that option is for if there is no palette at all. What I mean is that there is a palette, but you have none of the items of said palette in your inventory, you should go to inventory because the palette is effectively pointless.

For example, choosing to swap on "Sand" would bring up a palette for sand even if no other items are present
![image](https://github.com/tr7zw/ItemSwapper/assets/70297682/8518642e-c7e9-4beb-80d2-250156d72b18)

**Comment by tr7zw** [comment]
That still makes sense since you might want to a comparable item(sand or other items might be in multiple palettes/some other related item).

Anyway, an "always inventory" option has been added.

**Comment by Boden-C** [comment]
> That still makes sense since you might want to a comparable item(sand or other items might be in multiple palettes/some other related item).

Hmmm I still think it would be nicer, especially for items like Brewing where if you don't have any other items it could be safe to assume you don't need to swap to them. But I mostly care about the always inventory, so your choice.

Side note, you said "without rp" are you making the inventory default is possible with the resource pack? I thought the resource pack was for customizing your palette not for functionality like this

**Comment by tr7zw** [comment]
Without RP the mod will complain that you don't have any pack loaded. But turning on the option that you want to always open the inventory now bypasses that warning. Had people that wanted to use the mod for Vivecraft where the mod is simpler to use than the vanilla inventory(or people with disabilities). This way they don't need to make a dummy pack if they just want the inventory functionality.

**Comment by Boden-C** [comment]
Ah didn't know that, thanks

**Comment by tr7zw** [comment]
Two birds with one stone :D
