### ISSUE TITLE
[BUG] Some items in lists render invisible when selected at certain GUI scales

### ISSUE THREAD

**Issue by pajicadvance** [tr7zw/ItemSwapper#208]
### Version information

itemswapper-fabric-0.6.1-mc1.20.1

### Other relevant installed mods

fabric-api-0.92.1+1.20.1

### Expected Behavior

All items should be visible when selected in the list

### Actual Behavior

Some items (seems like the first two from the bottom) are invisible when selected in the list

### Reproduction Steps

1. Set the GUI scale to something not the power of two (?) (on my 1080p display the bug can be seen on GUI scale 3)
2. Put a tool in the hotbar, and add 3 or more other tools to the inventory
3. Press the hotkey to open the overlay with the tool in the hotbar selected
4. Observe that the first two items from the bottom appear invisible when selected
![image](https://github.com/tr7zw/ItemSwapper/assets/32738446/9a384ad4-bd9d-4425-8e28-879ad1aa9de0)
![image](https://github.com/tr7zw/ItemSwapper/assets/32738446/3087e6ca-3d58-4d28-b6a4-17459660cfe2)
Third item from the bottom and above render correctly
![image](https://github.com/tr7zw/ItemSwapper/assets/32738446/88cc2e33-211c-426b-a100-ab28dbe8ab93)

### Render engine

- [X] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Additional information

I don't recall seeing this bug before 0.6

**Comment by tr7zw** [comment]
Will need more time to investigate this layering issue(probably?). But also affects the other mc versions.
