### ISSUE TITLE
[BUG] Unable to join SINGLEplayer world (1.20.4)

### ISSUE THREAD

**Issue by Ghozgul** [tr7zw/ItemSwapper#213]
### Version information

ItemSwapper 0.6.3

### Other relevant installed mods

Quilt 0.26.0 | Quilt Fabric API 9.0.0 | ModMenu 9.2.0-beta2 | Sodium 0.5.8, with lithium and Indium | Carpet, tweakeroo ect

### Expected Behavior

Joining a singleplayer world

### Actual Behavior

Upon loading the world, an error appears with **"Connection Lost, Server sent an invalid packet"**, with the only option to get back to the **server list** even if I was in singleplayer. 
edit: my previous 1.20.4 modlist was using Quilt with Fabric API and ItemSwapper 0.5.5, but same thing happens if I load Quilted Fabric API.

### Reproduction Steps

Load mod with Quilt (seems to be the issue)
Play your singleplayer world

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

**Comment by tr7zw** [comment]
I won't look into quilt issues. I know there are issues with the networking right now, but it certainly works on Fabric singleplayer.
