### ISSUE TITLE
Support 1.21

### ISSUE THREAD

**Issue by jptrzy** [tr7zw/ItemSwapper#215]
### Is your feature request related to a problem?

Lack of the support for Minecraft 1.21

### Describe the solution you'd like

Add support for Minecraft 1.21

### Additional context

*This is issue is mostly a reason for discussion and a way to ask a question, if porting to 1.21 is planed?*

**Comment by tr7zw** [comment]
Is already merged, just not yet published.

**Comment by jptrzy** [comment]
Thanks
