### ISSUE TITLE
[BUG] first slot of inventory not recognized in palette

### ISSUE THREAD

**Issue by yehsi2000** [tr7zw/ItemSwapper#218]
### Version information

itemswapper-fabric-0.7.0-mc1.20.4

### Other relevant installed mods

modmenu-9.2.0-beta.2

### Expected Behavior

First slot of pickaxe should be visible in related item palette
![image](https://github.com/user-attachments/assets/bd6c74b2-efe8-4a40-816e-edcf0e963549)

### Actual Behavior

First slot is always undetected in related item palette not only pickaxe but also every tool and item
![image](https://github.com/user-attachments/assets/9e23f026-1d50-4b6e-9bb2-3c7a8ffc8396)
![image](https://github.com/user-attachments/assets/9795e945-061a-42c3-821d-af0adcea7c7c)

### Reproduction Steps

Just put any related item in first slot of the inventory and it will not appear on the related item palette
Moving item to different slot will display the item normally

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

**Comment by mageowl** [comment]
I am also having this problem.
