### ISSUE TITLE
idk how to renable use on a server

### ISSUE THREAD

**Issue by TheMiningKing26** [tr7zw/ItemSwapper#219]
i accidentally pressed esc, thinking it wouldnt disable it, yet it did, and  i cant find any info an how to reenable the use for the server

**Comment by tr7zw** [comment]
Via the settings screen of the mod.

**Comment by TheMiningKing26** [comment]
i looked in the config but i couldnt find anything

**Comment by TheMiningKing26** [comment]
nvm i found it. thank you
