### ISSUE TITLE
Unavailable items not greyed out with Iris

### ISSUE THREAD

**Issue by Xoouu** [tr7zw/ItemSwapper#22]
Currently all items in the category are shown as available even though they are not present in the player's inventory/shulker.
![image](https://user-images.githubusercontent.com/73406225/205449937-0a58df4e-2704-4ab9-9398-e12a6abcb552.png)

My inventory:
![image](https://user-images.githubusercontent.com/73406225/205449953-30c33db8-550d-44bb-b3a3-325c2a0cbadb.png)

Has anything changed between the video of xisumavoid and the current version? Maybe some mod incompatibility?

**Comment by tr7zw** [comment]
Known issue with Iris right now. Have it on the todo to fix.

**Comment by Xoouu** [comment]
I found my problem. It seems the mod uses the gamma/brightness setting to create the greyed out effect. If the user has set a brightness value way above of what is allowed without editing options.txt the effect disappears.

Maybe setting a limit or fixed value of the brightness used might help?

**Comment by tr7zw** [comment]
Fixed, now will have a red background instead.
