### ISSUE TITLE
Is there a plugin for 1.21?

### ISSUE THREAD

**Issue by UANe100** [tr7zw/ItemSwapper#224]
### Is your feature request related to a problem?

Is there a plugin for 1.21?

### Describe the solution you'd like

Is there a plugin for 1.21?

**Comment by tr7zw** [comment]
Just use the plug in. Doesn't need to be flagged for 1.21.

**Comment by UANe100** [comment]
> Just use the plug in. Doesn't need to be flagged for 1.21.

OK. Thank you.
