### ISSUE TITLE
[BUG] Not working on 1.21.1 Server

### ISSUE THREAD

**Issue by Meuserk** [tr7zw/ItemSwapper#229]
### Version information

itemswapper-fabric-0.7.1-mc1.21

### Other relevant installed mods

modmenu-11.0.2, fabric-api-0.104.0+1.21.1

### Expected Behavior

To swap my pick with my shovel.

### Actual Behavior

It says its not Working on this server But on my 1.20 Server i have every settig in server.propertys the same why not working
![Bild_2024-09-15_152102425](https://github.com/user-attachments/assets/31fa931d-92bf-4e4c-91e1-9e0b014809ab)
How can i fix it

### Reproduction Steps

Just pressing "R"

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

**Comment by tr7zw** [comment]
You have it disabled for the server. Go into the mod settings, at the bottom is a blacklist button and remove the server from the blacklist. Alternatively, go into the config folder, find the ``itemswapper-server-cache.json`` and either correctly delete the server there or just delete the file to reset all whitelists/blacklists.
