### ISSUE TITLE
is there a way to re-enable the mod for a server if you disable it?

### ISSUE THREAD

**Issue by Bitcode1134** [tr7zw/ItemSwapper#230]
i accidentally disabled it for the server im in and i would like to know if there is a way to turn it back on.

**Comment by tr7zw** [comment]
Via the config screen or via the file in the config folder.

**Comment by drakosoldier298** [comment]
Where in the config/ config screen?

**Comment by tr7zw** [comment]
Update is out, accessing the normal config screen via the modlist now has it neatly.
