### ISSUE TITLE
Feature request: MidnightControlls support

### ISSUE THREAD

**Issue by Mathew420w0** [tr7zw/ItemSwapper#24]
Add the ability to change controls of the item selection; I specifically would like it if, instead of using the mouse to select the item from the menu, you could use the arrow keys. Another thing; it would be great if it worked with MidnightControlls mod so that it doesn't conflict with the joystick controls. I experimented on a SteamDeck and would like to integrate it with Steam Controller Settings, but the mod doesn't detect the mouse yet; instead of the menu, it moves the character view. 

In an ideal setup, I would have some Steam Radial menu activated by the R5 button, and from there, select the items with the trackpad.
I don't know how to integrate this feature, but it's an idea that I haven't figured out.

**Comment by tr7zw** [comment]
Hmmm this one is tricky. I do have a Steam Deck, but I don't have Minecraft installed to it/any experience with how to handle that input. This might be a longer/more tricky question. What does it currently do, when holding/pressing the configured button, and then using the joystick/trackpad(whichever is used for normal mouse/camera movement)?

**Comment by Mathew420w0** [comment]
The menu works fine on a standard desktop with a mouse and keyboard. Still, with a trackpad, which is mapped through the MidnightControlls mod, it ignores the menu and moves the view instead of moving only the selector as it should; I tried using Steam's own action sets to see if I could tweak the controls to ignore the view controls when I activate the menu, but I wasn't successful, (I also don't use mouse mode for the trackpads nor joysticks, they're both set to joystick)

**Comment by tr7zw** [comment]
It sounds like the MidnightControlls mod bypasses the location where I grab the mouse inputs, and inserts them at some later place. Could become tricky, but certainly something to look into.

**Comment by martinkadlec0** [comment]
I had similar thought that it might be neat if you could scroll through the items using mousewheel instead of moving the mouse.

**Comment by tr7zw** [comment]
The mouse wheel does already work.

**Comment by martinkadlec0** [comment]
@tr7zw I've tried both toggle and non-toggle mode and using mouse wheel does nothing (v0.3.1). Anything I can do to help debug this?

**Comment by tr7zw** [comment]
On lists, mouse wheel to scroll certainly works? Huh.

**Comment by martinkadlec0** [comment]
@tr7zw Oh, so it is supposed to work on lists but not on grids right? I was thinking it would be nice on grids too (going row by row).

**Comment by tr7zw** [comment]
Huh, does it make much sense for the grid? I guess I can do that.

**Comment by martinkadlec0** [comment]
To me it would feel more intuitive so I would appreciate it.

**Comment by KairuDeibisu** [comment]
The referenced ticket may be confusing.

I misremembered the controllable mod as the midnight controls mod.

Midnight controls is for fabric.

Controllable is for forge. We can ignore the controllable mod.

To summarize the reference ticket, The main issue is how buttons are being bound, making it hard or impossible (needs to be tested) to bind buttons to the controller through the midnight controls mod.

**Comment by tr7zw** [comment]
Yea, the middle and left click currently have no good way to getting mapped to a controller. I'll have to look into how the MidnightControlls mod works. Same issue with the cursor movement.

**Comment by KairuDeibisu** [comment]
Here's the results of my investigation.

The midnight controls mod can absolutely see item swapper key binds.

I rebound opening item swapper from r to up on the d-pad on my Xbox One controller. 

I also enabled toggle open.

This is where the problems begin. The menu would open up. But the analog sticks wouldn't move around the window. 

You still have full control of your character and could look around.

It appears, midnight controls, It may bypass the mouse.

This is probably why it was suggested to allow us to navigate the menu using keybinds as well. 

The best solution is to figure out how midnight controls is bypassing the mouse for the analog sticks.


## midnight controls background
A little background of midnight controls.

Midnight controls allows you to use analog movement or keyboard movement mapped to the analog stick.

It also allows you to use the mouse or a virtual mouse.

**Comment by tr7zw** [comment]
https://user-images.githubusercontent.com/5133936/210875939-6db4e0cf-e641-4da7-a847-9a1ffa943f31.mp4

I am pushing a first draft into the current dev branch. I tested with an Xbox controller, using the d-pad up to show the UI, X as middle-click, and the right joystick to move the cursor. I have no clue how well these controls translate to the deck(I haven't installed MC there) or other controllers. One thing I noticed, is that the joystick pull rate is really low, making the cursor somewhat choppy. Please give feedback on how it can be improved(download the latest build from the ``1.19`` branch in [Actions](https://github.com/tr7zw/ItemSwapper/actions) for testing). Also thank you Kyle for the amazing Ko-Fi donations to prioritize this

**Comment by Mathew420w0** [comment]
This works perfectly on the Steam Deck! I managed to do all the things you did, and I did change the controls because I already had DPAD up occupied, so I used R3 on the back of the steam deck, it works excellently, and I can imagine it can work great with any other controller, thanks!

**Comment by tr7zw** [comment]
Oh yea, since the Steam Deck has so many more buttons(4 alone on the back), that makes it a lot simpler. I used the Xbox Controller, so my selection of buttons was really limited, especially since no button combination was possible(all L/R/joystick buttons are already used).

**Comment by tr7zw** [comment]
Going to close this issue, since it mostly has been resolved. Further improvements can be done incrementally when new issues show up.
