### ISSUE TITLE
Default sorting changes

### ISSUE THREAD

**Issue by KitsuneNoNatsu** [tr7zw/ItemSwapper#26]
Will the default swapper be linked to the 1.20 inventory changes, with having categories and sub categories, and would doing so allow mod makers easier access to implementing their items into this mod

**Comment by tr7zw** [comment]
The lists are designed with the 1.19.3 changes in mind. Other than that, it's entirely unrelated to the categories/sub categories of the creative menu. Mod makers can just include json files in the correct places, to add support, no dependencies/code is needed.
