### ISSUE TITLE
Copper wheel is buggy

### ISSUE THREAD

**Issue by M10241024** [tr7zw/ItemSwapper#28]
Copper wheel should change between oxidation levels but instead it changes between normal <=> oxidized and exposed <=> weathered copper. When middle clicking on normal or oxidised slab it changes to all copper slabs wheel instead

**Comment by tr7zw** [comment]
Already fixed in the dev build. Give it a try by downloading it from the Actions tab above (https://github.com/tr7zw/ItemSwapper/actions/runs/3609474007 right now).
