### ISSUE TITLE
Option to disable keybind while in inventories.

### ISSUE THREAD

**Issue by AmyMialee** [tr7zw/ItemSwapper#31]
The R key feels like the best key for this mod, but that causes issues when you're in a chest etc since R is the most common keybind to view an item's recipe.
A config option to have this only work without a screen open would solve the conflict, and ynow if i'm in a chest i can just move the item myself.

**Comment by tr7zw** [comment]
It works while having a chest open? Welp, that's clearly a bug.

**Comment by AmyMialee** [comment]
Oh I see, it felt intentional.
In that case it could be an incompatibility, maybe with [InvMove](https://www.curseforge.com/minecraft/mc-mods/invmove).

**Comment by tr7zw** [comment]
I forgot to add a check on if a screen is open.

**Comment by Golder06** [comment]
Similar issue is that you can press keys that make other screens pop-up while in the Item Swapping Menu is open, like ESC for the pause menu, E for the inventory and T for chat.
ESC only works with the Toggle Mode on, but E and T work regardless.

**Comment by tr7zw** [comment]
I mean these I don't find that bad. ESC should just cancel the interaction(currently doesn't), and E/T is a bit of undefined behavior. Will have to think about it.

**Comment by tr7zw** [comment]
Hm, I cant get this to work at all. Inside inventories, the keybind does nothing. The only thing I get is ESC opening the pause menu instead of closing the UI, and when pressing e, the inventory opens after the UI closes.

**Comment by tr7zw** [comment]
Esc now does behave correctly. Also added a sanity check, preventing the UI from opening while anything else already is open(like a chest with invmover).
