### ISSUE TITLE
Screen freezes while item swapper menu open with Optifabric.

### ISSUE THREAD

**Issue by A1ver** [tr7zw/ItemSwapper#33]
Hello! 
I encountered a problem while using the itemswapper mod with Optifabric.
The itemswapper menu works perfectly fine, but while its open the screen freezes. I am still able to walk around but the screen only un-freezes once the menu is closed again. Unfortunatly, I coulndt find an option that affects the issue in any way. 
Versions are: 

fabric-api0.68.0+1.19.2
itemswapper-fabric-0.3.1-mc1.19.2
optifabric-1.13.16
Optifine_1.19.2_HD_U_H9

The issue dissapeares after removing optifine and optifabric. There are no other mods or shaders installed.

A screenshot with the menu open, and an achievement message: 
Curiously, the advancement message leaves the screen just fine(while the rest is frozen), but leaves behind a trail of itsef while sliding out, apparently in sync with my (low)framrate. 
I hope it helps identifying the problem.

![2022-12-03_18 39 46](https://user-images.githubusercontent.com/100602337/205455168-1b08908b-74d9-46b4-8c05-b147e6e007c2.png)

**Comment by JanHeimsoth** [comment]
Damn, I got the same issue.

**Comment by tr7zw** [comment]
Like I mentioned on the other Optifine-related issue, I don't use or test with Optifine, and since it works fine with Vanilla and Sodium, these are fun issues introduced by Optifine. I'll look into it at some later point, but the better solution is to just not use Optifine.

**Comment by tr7zw** [comment]
Should be fixed.
