### ISSUE TITLE
Cursor movement (with the invisible cursor) can be confusing in the 12 item menu (and possibly other non square shape menus)

### ISSUE THREAD

**Issue by PartyWumpus** [tr7zw/ItemSwapper#37]
This is a very specific issue, possibly not worth the effort it could take to fix it.

In the first image, I have moved my cursor to the top left (with visible cursor off), and the dispenser is selected. Intuitively, I expect the cursor to look like either image 2 or image 3 so when i move my cursor to the right, I expect the dropper to be selected. But, obviously, as the 4th image is what the cursor actually looks like, I select the hopper instead. This is confusing.

![image](https://user-images.githubusercontent.com/48649272/205462055-c2dcaa2b-4f1a-4a99-a77f-81dad8ff6620.png)

The solutions I can think of are either:
- just making the cursor enabled by default, and not really worrying about this non-issue when using a non-default setting
- make it so each selection window has a 'mouse bounding box' that isn't just a square and instead matches up with the window. One issue with this is that it would be odd when the visible cursor is enabled, so maybe make it a toggle or only on when the cursor is off? Might also cause issues for texture packs, but I'm not certain about that.

**Comment by tr7zw** [comment]
I plan to make it on by default. It being off by default is from the time, when 8 slots in a ring were the maximum. And I was thinking about using a bounding box, but that is not forgiving enough when overshooting it slightly. Right now it uses the distance from the middle of the box and does a distance check. Adding a limit to the distance might fix such odd behavior like the top left selecting the dispenser(on the other hand, might be confusing without a cursor?)

**Comment by tr7zw** [comment]
This has been resolved.
