### ISSUE TITLE
Pressing the Inventory "E" key while in a selection opens the inventory afterwards

### ISSUE THREAD

**Issue by mfkoerner** [tr7zw/ItemSwapper#38]

**Comment by tr7zw** [comment]
Duplicate of #31

**Comment by mfkoerner** [comment]
From what I can tell this is the reverse order of #31 but they probably share a fix!

**Comment by tr7zw** [comment]
Yea, while anything is open, ignore the R key, and the other way around, ignore the E key while this is open.

**Comment by CTNOriginals** [comment]
This still seems to be an issue...
I looked at #31 too but the bug explained in there does not apply anymore while this one still does.
So to re-iterate, having the itemswapper menu open and then pressing the open vanilla inventory button (`E`) will not open the vanilla inventory but instead causes the vanilla inventory to open after closing the itemswapper menu.

What i would instead expect to happen: When pressing `E` while in the itemswapper menu, it should just cancel the itemswapper menu and open the vanilla inventory instead.

**Comment by tr7zw** [comment]
No, the correct behavior is nothing. Having itemswapper open shouldn't allow the inventory keybind to do anything.
