### ISSUE TITLE
Feature Request: A checkbox for including nearby storages.

### ISSUE THREAD

**Issue by dragon3025** [tr7zw/ItemSwapper#39]
When a list or wheel interface is up, there would be a nearby checkbox for including nearby storages. It would also include shulker boxes inside them, but if that feature is laggy then maybe it would deserve its own checkbox.

**Comment by tr7zw** [comment]
Uhhh that would go really hard against the current vanilla-like concept. Probably won't be something to be considered in the near future.

**Comment by dragon3025** [comment]
Ah alright, I thought it would be like pulling out of nearby chest, but one could always just filter and sort them.

**Comment by tr7zw** [comment]
It only pulls from shulkers inside the inventory, not placed ones. There are mods that do that, maybe look into them.
