### ISSUE TITLE
Support for multiple empty fields in wheel selection

### ISSUE THREAD

**Issue by 2mal3** [tr7zw/ItemSwapper#4]
Currently, the game always crashes when adding a new wheel where several fields are empty (there are no problems if only one field is empty). 
This would be handy, since some wheels (for example one with Cobblestone, Cobblestone Stairs, ...) are currently impossible to implement, because they don't have exactly 8 variants.

Example resource pack: [cobblestone.zip](https://github.com/tr7zw/ItemSwapper/files/9932377/cobblestone.zip).

**Comment by tr7zw** [comment]
Yea, that was an unintentional off-by-one bug in the code. As a note, we are still testing out layouts/designs/slot amounts, so this might also change. Currently, it just picks the 8 slot one if <= 8, and a16 slot one if it's any more(wool has that setup for testing). It is fixed in this new build.
