### ISSUE TITLE
[Bug] Rebinding Switch Item key to a mouse button breaks non-toggle mode.

### ISSUE THREAD

**Issue by martinkadlec0** [tr7zw/ItemSwapper#40]
I've tried binding the Switch Item key to one of my side mouse button (Button 5), but when the toggle mode is turned off the popup won't disappear when I stop holding the mouse button, instead it acts as if the toggle mod were on. Also once I select something I need to press the mouse button two times for the pop up to appear again.

Mod version: v0.3.1
Minecraft version: 19.2
Mouse: Hyperx Pulsefire (very standard, nothing special)

**Comment by lgowen22** [comment]
I did the exact same thing and the same problem happened. I thought toggle mode was just stuck on or something but good to know it's just a mouse button thing. Still, it should be fixed.

**Comment by ShaneTRS** [comment]
Can also recreate the issue on Linux using Quilt Loader 0.17.7

**Comment by tr7zw** [comment]
That seems to be how Minecraft handles mouse buttons. nothing I can do about this(it just sends a single click, not that it's held down). For now, only toggle mode works with the mouse.
