### ISSUE TITLE
Tapping hotkey with nothing in hand moves the item from slot 9 to the active slot

### ISSUE THREAD

**Issue by drisch314** [tr7zw/ItemSwapper#42]
To repeat this issue:
1. Put an item / stack in slot 9 of the hotbar
2. Have a different hotbar slot active / selected
3. If toggle mode is on, press the hotkey, don't move the mouse to hover over any itemswapper slots, press the hotkey again. If toggle mode is off, simply tapping the hotkey without moving the mouse will have the same effect (because the HUD automatically closes when you let go of the key).
4. The items in hotbar slot 9 get moved to the (previously empty) active hotbar slot.

Basically, when exiting the ItemSwapper menu with nothing in your hand (which shows the inventory items), and not moving the mouse at all in the ItemSwapper HUD, the items in hotbar slot 9 move to the active selected hotbar slot. I don't know for sure that this is unintended behavior, but it seems odd and not very useful. 

Disclosure: I do have other mods installed, so I'm not 100% certain that the other mods didn't cause this behavior somehow. But I don't see how any of them would. Testing on a cleaner system is required to make sure it is an issue with _this_ mod specifically.

**Comment by tr7zw** [comment]
I've had it pull unintended items, but never reproducible. If I can reproduce it with these steps, I can look into what's going on.

**Comment by drisch314** [comment]
Huh, yeah hopefully it's not just a result of my melting pot of rando mods, but is an actual lead. I wish you luck

**Comment by tr7zw** [comment]
No, can confirm it. I guess it's some stupid missing bounds check, default selection is -1, it might try to calculate the slot based on the top left + (-1) = the 9th slot. Just a rough guess of what might be going on.

**Comment by drisch314** [comment]
Ah yeah those can be annoying; seems like you're on the right track though
