### ISSUE TITLE
Game crashes with litematica installed

### ISSUE THREAD

**Issue by NightMix80** [tr7zw/ItemSwapper#46]
I had installed the mod with a few others i was adding to my pack primary litematica and a few loading opt mods ended up removing those which just lets me with this and litematica. Was using litematica-fabric-1.19.2-0.12.5.jar along with it its a shame i cant run both. or maybe its just an odd conflict with other mods i have idk but would love having both mods work nicely with each other any who
here's the logs for the crash at first i thought it was something else but ended up isolating to just litematica

(file below has the mod)
[hs_err_pid17652.log](https://github.com/tr7zw/ItemSwapper/files/10148123/hs_err_pid17652.log)

(this also has it plus another mod i had installed i though was the issue)
[hs_err_pid16416.log](https://github.com/tr7zw/ItemSwapper/files/10148124/hs_err_pid16416.log)

[mods.zip](https://github.com/tr7zw/ItemSwapper/files/10148125/mods.zip)

**Comment by tr7zw** [comment]
Uhm, that crash happened inside litematica during OpenGL calls. This mod doesn't touch anything OpenGL related, might be better to ask over at the litematica repo.

**Comment by Bloemist** [comment]
Can confirm it works with litematica (fabric) for me without issues.

**Comment by tr7zw** [comment]
Yea, going to assume this is something unrelated.
