### ISSUE TITLE
Add a button to send an item from hotbar to inventory

### ISSUE THREAD

**Issue by ChilledW** [tr7zw/ItemSwapper#47]
Is there a way you could implement a way to send items back to your inventory form your hotbar.
Curently the feature of accesing your whole inventory when you press 'r' with an empty hand isn't usefull because the empty slot gets filled and you have to open your inventory to remove the item from the slot

**Comment by tr7zw** [comment]
Was added.

**Comment by AstudilloMarillo** [comment]
A dedicated configurable hotkey for this would still be great.
