### ISSUE TITLE
[Sugestion] changes to resoucepack customization

### ISSUE THREAD

**Issue by M10241024** [tr7zw/ItemSwapper#48]
1. Move all files to the same folder - if item is present in multiply first one will be primary wheel, second will be scondary wheel etc.
3. More customization options:
```
{
    "type": "list",
    "length": 5, //optional
    "items": [...]
}
```
```
{
    "type": "wheel",
    "shape": [
        "||",
        "# #",
        "||"
     ] //optional, # for item slot, space for hole, | for right shifted slot, _ for downwards shifted slot, L for both
    "items": [...]
}
```
In the example above, wheel will look like 6-item wheel with hole style on.
Combined this will allow to have some items in both lists and wheels.

**Comment by M10241024** [comment]
also another optional field:
```
{
    "type": "wheel",
    "priorities": ["stone"],
    "items": ["stone","stone_slab","cobblestone"]
}
{
    "type": "wheel",
    "priorities": ["cobblestone"],
    "items": ["cobblestone","cobblestone_slab","stone"]
}
```
When pressing R while holding stone it will open first wheel, but when using cobblestone it will open second.
Question: what determines which wheel is used when item is present in multiply with current system?

**Comment by M10241024** [comment]
Basicly I want 3 things and thats my idea of implementing them:
1. Custom shapes
2. Item in more than 2 wheels (+priorities)
3. Item in lists and wheels

**Comment by tr7zw** [comment]
> Item in both lists and wheels

And how would you imagine that working?

> Custom shapes

That could at best use the fallback render logic using the offhand slot. Not sure if the added complexity is worth it?

**Comment by M10241024** [comment]
> And how would you imagine that working?
Just middle click to switch between diffrent lists and wheels.

**Comment by tr7zw** [comment]
Current internal reworking of the format is in progress, but currently, neither custom shapes(unless you are a modder) nor items in both lists and wheels are planned(since that makes no sense from a practical point of view, and wouldn't work in practice).

**Comment by tr7zw** [comment]
Closing this, as this more or less is implemented. More changes to the format are not planned for now.
