### ISSUE TITLE
[SUGGESTION] My version of textures (And new problem with textures)

### ISSUE THREAD

**Issue by ViTulyankin** [tr7zw/ItemSwapper#49]
Sooo... From the time when I asked to return old textures and understood that it is impossible, I was trying to improve your new version. And now I can say, that I've finished.

![image](https://user-images.githubusercontent.com/92220631/205494344-83d13c1a-15d7-4b6a-80a2-de54a82402a4.png)

![image](https://user-images.githubusercontent.com/92220631/205495137-b4c97b9e-1e87-45a8-b9f0-6fb4e4d16262.png)

The 'hole' variant

![image](https://user-images.githubusercontent.com/92220631/205495100-1938a458-08f5-4ba9-a6da-2d3bec585bb5.png)

Item list

![image](https://user-images.githubusercontent.com/92220631/205496091-7c2a061e-5618-450d-8db1-95d6b84f09f0.png)

I can't show all textures, but everything was remade.

Misalignment (issue #13) was fixed, now position of the item it is more vanilla-like. Textures now feels more like a hotbar (maybe because I litteraly took textures from there). It is also one pixel smaller in both width and height.

I changed selection box to default one and found new misalignment** - selection box is shifted to the right by one pixel (only in item wheels and inventory).
Also, selection box is rendering under items (maybe not a bug, considering that in your textures it must be underneath them)

![image](https://user-images.githubusercontent.com/92220631/205495317-1070b235-11ea-417b-a77d-801047abe074.png)

I dunno why I made this, more just for myself, but maybe this will help you to make next version of textures better :)

**Comment by tr7zw** [comment]
Uhh, not sure if this is the best time to make custom textures, since due to size fail, the entire item positioning will change once we get around to fixing the textures. Another noteworthy point, the 'hole' variant will be gone next release, so don't bother to tinker with them for now. I guess including an optional alternative UI art style would be possible, will have to ask Xisuma about his opinion. (Basically programmer art)

**Comment by tr7zw** [comment]
Ok update: we'll keep it 18x18, with 16x16 for the slot(and a one-pixel outline).
