### ISSUE TITLE
[Suggestion] Changes to secondary wheel to have items in multiple wheels

### ISSUE THREAD

**Issue by ValentinZeller** [tr7zw/ItemSwapper#50]
The major issue of the mod right now can be seen with the sea lantern:
the sea lantern is in the prismarine wheel but we want to have it in the lights wheel, currently we have to create a secondary wheel that have the sea lantern and one (or all) item of the lights wheel but it's obviously not a good solution as it creates redundancy.

My idea is inspired by the new combined wheel feature that have more than 2 pages: 
Instead of having secondary wheel, all primary wheels should be declare in the same folder and in the secondary wheel folder, we declare a json file per items that are in multiple wheels and that define the order of the wheels, for example:
we have a sea_lantern.json file that could look like this:
```JSON
[
    "prismarine",
    "lights"
]
```
With this, 'R' open the prismarine wheel and when the mouse hovers the sea_lantern, the middle mouse button switch to the lights wheel.
Using a second time the middle mouse button will try to switch to the next wheel in the list of the selected item and when there is none, it switch back to the first wheel in the list, in this example, the prismarine wheel.

But it may overlaps with combined, for example:
secondary wheel white_wool.json :
```JSON
[
    "white",
    "wool"
]
```
primary wheel white.json :
```JSON
[
    "white_wool",
    "white_carpet",
    "white_concrete_powder",
    "white_concrete",
    "white_stained_glass",
    "white_stained_glass_panel",
    "white_bed",
    "white_banner",
    "white_candle",
    "white_dye",
    "white_terracotta",
    "white_glazed_terracotta"
]
```
To switch from white wool to red carpet: 'R' to go to item switcher menu, mouse hover the white_carpet, 'Middle MB' to switch to the carpet wheels and selected the red_carpet.
So, with this, is there still some cases where combined wheel is better ?

**Comment by tr7zw** [comment]
Something kinda like this is planned, the exact design is still a bit open.

**Comment by tr7zw** [comment]
It's not this exact implementation, but the palettes now work differently.
