### ISSUE TITLE
Add arrow or scrollbar to list slots

### ISSUE THREAD

**Issue by AdvancedWipe** [tr7zw/ItemSwapper#53]
I think, it is a good improvement to add some kind of icon to the list slots (at least that's the name in the resource pack for the textures) to make it more clear that the list goes on.

![grafik](https://user-images.githubusercontent.com/65723138/205503908-665366db-4566-4754-be7a-4961132418b7.png)

I think that some kind of arrow (like the one in the texture pack selection to move the packs up and down) or even some kind of scrollbar (like the one in the creative menu), would give the player a better visual feedback to continue moving the mouse down. I know the bottom/ top of the last or first slot is missing if there are more items in the list, but I guess it could be much clearer.

**Comment by tr7zw** [comment]
I think this is pretty clear, that the list continues there, but might be biased. I guess letting others comment on it might help.

**Comment by SebSemos** [comment]
I think it's clear, but I cn see in rush situations not seeing the difference as well. I'm up for a little arrow pointing down too :)

**Comment by ViTulyankin** [comment]
I also think it's already clear, especially considering that you first have to scroll up to get to the top.

**Comment by tr7zw** [comment]
This might be better placed inside a resource pack that just modifies the texture to your liking I guess. Reopen the issue if necessary.
