### ISSUE TITLE
[Suggestion] A way to open the inventory preview with an item in hand

### ISSUE THREAD

**Issue by 22demerathd** [tr7zw/ItemSwapper#57]
A way to open the inventory preview with an item in hand.

Would be useful so you can swap two things that don't necessarily share a pallet, or return things to your inventory (by releasing the button while hovering on an empty slot).

**Comment by SebSemos** [comment]
What difference from vanilla opening the inventory tho?

**Comment by 22demerathd** [comment]
> What difference from vanilla opening the inventory tho?

The same question could probably have been asked about the whole mod, why not just open your inventory to get the oak stairs?

imo the answer to both questions is convenience, it’s convenient, and fast, and allows you to not just grab something, but swap it for something in your hotbar instead, saving you the time to need to put that thing back in your inventory.

**Comment by piebaker** [comment]
Could not agree more with this suggestion, i just need access to my inventory to grab a random block at any time, and the palate system doesn't take that into account, or mods. Having a config option to simply disable palates would be awesome

**Comment by tr7zw** [comment]
Oh this is a duplicate. Like I mentioned on the other ticket about the same thing, this is resolved in the dev branch/future versions. No new key, but a new button in the ui to move the hand item to the inventory, so it opens the inventory next. Maybe a new ui button for the inventory later, but shouldn't be needed.

**Comment by tr7zw** [comment]
#77 for reference.
