### ISSUE TITLE
Idea: Numeric Control With Tool/potion Switching 

### ISSUE THREAD

**Issue by apicella1** [tr7zw/ItemSwapper#6]
Being able to press a number on the keyboard could allow for easier Switching for the first  handful of switchable items.

  I do understand however that it's difficult to press r and anything after six since you'll be utilizing your pointer finger to press the R key most of the time, hence why it may be easier for just the first 5, or handful of keys. Either way, this may make it way better and more efficient if you're just going for those said 5.  
  
We also should take into consideration that some people's way of playing the game is different and I do know that hotbar selection through numbers is used more than I understand it being. I could just very much be looking at this through a biased perspective, or the conversation of the issue isn't discussed as much.  Whatever it is, I think playing with  this mod has made me realize how important this system is and how much easier things could possibly be with numeric control. 

I guess the thing that would need to be worked on is, If it's descending or ascending, up or down? I Would suggest to make 1 be the closest to the hotbar and 5-9 to the furthest.

**Comment by apicella1** [comment]
For All I know, this selection could also work with the Wheel Setup too for nums 1-8 Maybe going in a left to right order.

**Comment by tr7zw** [comment]
Not sure how well that would work, since nearly half of the options are missing a number. Would be odd when you can switch to the first 9/10 items, but not the last 6/7 ones.

**Comment by tr7zw** [comment]
This simply doesn't apply anymore to the current builds of the mod(there are way more than 9 slots), so closing this issue.
