### ISSUE TITLE
[Bug] Suddenly unable to open item swapping GUI.

### ISSUE THREAD

**Issue by xopowohiro** [tr7zw/ItemSwapper#62]
Unsure how this happened, but for some reason the mod's main feature stopped working entirely, leaving me only with the option to pick items from my inventory. If I had to make a guess I'd say it probably occured after changing my keybind from R (which was set to sprinting) to M. Re-installing the mod didn't change anything.

**Comment by tr7zw** [comment]
Check that the resource pack is loaded.
