### ISSUE TITLE
[Suggestion] List settings/functionality suggestions

### ISSUE THREAD

**Issue by pllot** [tr7zw/ItemSwapper#69]
1. Exclusively use the scroll wheel for list navigation: This would prevent conflicting inputs with unintended mouse movements and the scroll wheel. Also, the players viewpoint would no longer have to be locked and it would act more like a secondary hotbar

2. Lists could appear above the current slot, rather than always above the first slot. Could also move down to render over xp bar, hearts, etc. and look like an extension of the hotbar. Picture a crossword puzzle. Could look messy with some texture packs.

3. Horizontal lists: A side to side motion is easier and more natural with a mouse. Alternatively the lists could still be vertical and have a setting to accept horizontal movements.

4. Wrapping lists: Going past either end of the list loops to the other end.

**Comment by SebSemos** [comment]
Agreed! 
I used wild tool acces for quite some times now, and having camera locked when switching tools make me feels bugged ^^
Also genuinely not realised mouse was working with list at first glance. I went scroolwheeling so naturaly ^^

**Comment by tr7zw** [comment]
There is now an option to no longer lock the mouse in lists and only use the scroll wheel.
