### ISSUE TITLE
Cursor not showing in v0.3.2

### ISSUE THREAD

**Issue by SebSemos** [tr7zw/ItemSwapper#72]
It was working in v0.3.1 but don't show anymore in lastest version

**Comment by tr7zw** [comment]
It still works. Make sure the setting is turned on.

**Comment by SebSemos** [comment]
It is, I just realised it's a ressource pack conflict. I'll troublleshoot later what does it.

**Comment by tr7zw** [comment]
Currently, it uses the normal crosshair as the cursor.
