### ISSUE TITLE
[ISSUE] Shulker boxes wont load as a list

### ISSUE THREAD

**Issue by Stinkywaffle** [tr7zw/ItemSwapper#73]

**Comment by tr7zw** [comment]
Thaaats already in there?

**Comment by tr7zw** [comment]
Did you perhaps have the shulkers in the hotbar? Hotbar items are ignored for the list.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/208747781-49ac524c-1b28-4a98-a7a6-fcf5af78c697.png)
Going to assume you had them in the hotbar already. At least can't reproduce it.
