### ISSUE TITLE
[Suggestion] Allow entire Inventory access in config

### ISSUE THREAD

**Issue by Reddy64** [tr7zw/ItemSwapper#77]
May be nice to make it an option to allow the inventory in it's entirety to be accessed regardless whether or not having an empty hand, and able to select empty slots as well to put an item back.

This is mainly in modded contexts where a lot of items aren't supported, since adding support for these would most likely be time consuming and difficult (I've been using Create, but with the amount of blocks on that mod and how more utilitarian it is in nature, I believe this may just be a better option.)

**Comment by 619tmFALCON** [comment]
pretty sure community will make resource packs that support mods in the future

**Comment by tr7zw** [comment]
Future versions will contain a clear hand (or maybe also an "open inventory") button in the UI. Also like already mentioned, anyone can make resource packs for mods, so there are multiple ways for mods to be supported (community packs, mod owners adding support themselves, or modpacks where the modpack creators can make them).
