### ISSUE TITLE
Boxes are overlapping each other

### ISSUE THREAD

**Issue by Imzxhir** [tr7zw/ItemSwapper#8]
Basically the title. Here is an image: 
![image](https://user-images.githubusercontent.com/98621617/204876180-8e33108b-eddb-46a0-81d3-32fae0319fed.png)

**Comment by tr7zw** [comment]
Intended. The boxes are smaller than the hotbar to save space, so it gets layered in a way, that the selected item and selection are above the rest.

**Comment by tr7zw** [comment]
Wrote a bit with xisuma, mig

**Comment by tr7zw** [comment]
Also these pics from the mod page are just from an old version where it still used the offhand slot as background. Not a part of the mod anymore.

**Comment by tr7zw** [comment]
> Oh ok. What did you mean by 'Wrote a bit with Xisuma' in your previous comment?

This mod is based on this concept video https://www.youtube.com/watch?v=A6DvnFCW5FY .
