### ISSUE TITLE
Items are not cenetered

### ISSUE THREAD

**Issue by Imzxhir** [tr7zw/ItemSwapper#9]
Mod Version: v0.3.1
Description: The title. Here is an image: 
![image](https://user-images.githubusercontent.com/98621617/204891697-ffd744e4-9d55-45b2-9c11-48765ea134c0.png)

**Comment by tr7zw** [comment]
Technically not fixed, the current slot texture is 1 pixel to wide and tall.

**Comment by lgowen22** [comment]
It doesn't look fixed for me and I'm using the latest version. Items are still off center

**Comment by tr7zw** [comment]
> the current slot texture is 1 pixel too wide and tall.
