### ISSUE TITLE
[Feature Request] Using the swap button without a required pack enabled, gives notice to enable the pack

### ISSUE THREAD

**Issue by dragon3025** [tr7zw/ItemSwapper#94]
I thought the mod wasn't working, I kept pressing the key and nothing was happening, then I realized the pack wasn't enabled (I didn't disable it, so I don't know how that happened).

I think it would help if pressing the item swap button when a required pack isn't enabled gave a small text message saying something like "no item swap resource pack enabled".

**Comment by AdvancedWipe** [comment]
Which version of the mod are you using?

**Comment by AdvancedWipe** [comment]
Because in 0.3.2 something similar was added. https://github.com/tr7zw/ItemSwapper/releases/tag/v0.3.2

**Comment by tr7zw** [comment]
That has been in the mod since [0.3.2](https://github.com/tr7zw/ItemSwapper/releases/tag/v0.3.2). Duplicate #51

**Comment by dragon3025** [comment]
Ah, I'm still in 1.19.2 until some other mods update, so I'm using 0.3.1. I'm glad to see that was added in 1.19.3.

**Comment by tr7zw** [comment]
The 1.19.3 version is the 1.19.2 version. Development will stay on 1.19.2 for now too. You are on an old version.

**Comment by tr7zw** [comment]
https://modrinth.com/mod/itemswapper/version/v0.3.2 For reference

**Comment by dragon3025** [comment]
Ah, I'll update to 0.3.2 then.

I don't know if this is an error, but curseforge is saying it's for 1.19.3: https://www.curseforge.com/minecraft/mc-mods/itemswapper/files/4178243.

**Comment by tr7zw** [comment]
That's just the latest 1.19.* file. The one before with the same version number is for 1.19.2
