### ISSUE TITLE
Another texture issue

### ISSUE THREAD

**Issue by ViTulyankin** [tr7zw/ItemSwapper#97]
In 0.3.2 you changed texture of unavailable items:
• Instead of darkening the item for unavailable items, the background turns red like in the crafting grid

But in crafting grid it's not only background red, it's also an item slightly grey

Vanilla vs ItemSwapper:
![image](https://user-images.githubusercontent.com/92220631/208298449-81c73ffb-559b-4a13-b444-64f126b6daf2.png)

**Comment by tr7zw** [comment]
The white glow was removed because it looked really bad and just makes the items harder to read.
![grafik](https://user-images.githubusercontent.com/5133936/208304255-1a5524a7-5149-4ef1-aa28-55558696cb00.png)

**Comment by ViTulyankin** [comment]
Yeah, grey items look really weird, i didn't think about it
